name: pytf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - ipykernel
  - pip
  - pip:
      - notebook
      - nbconvert
