best_threshold: 0.33831683
hyperparameters:
  colsample_bytree: 0.7
  gamma: 5.0
  learning_rate: 0.1
  max_delta_step: 1
  max_depth: 4
  min_child_weight: 5
  n_estimators: 194
  reg_alpha: 10.0
  reg_lambda: 0.1
  scale_pos_weight: 5
  subsample: 0.7
