best_threshold: 0.315233051776886
hyperparameters:
  colsample_bytree: 0.4
  gamma: 2.0
  learning_rate: 0.075
  max_delta_step: 0
  max_depth: 2
  min_child_weight: 4
  n_estimators: 674
  reg_alpha: 0.0
  reg_lambda: 10.0
  scale_pos_weight: 5
  subsample: 0.9
